routes/web.php
<?php

use Illuminate\Support\Facades\Route;
require_once 'merchant-routes.php';
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::group(['prefix' => 'Board', 'middleware' => ['admin', 'lang'], 'namespace' => 'Board'],

function () {
		Route::get('/', 'BoardController@index')->name('board.index');
		Route::get('/language/{lang}', 'BoardController@change_language')->name('board.lang');
		Route::get('/logout', 'Auth\LoginController@logout')->name('board.logout');
		Route::get('/profile', 'ProfileController@index')->name('board.profile');
		Route::patch('/profile', 'ProfileController@update')->name('board.profile.update');
		Route::get('/password', 'ProfileController@edit_password')->name('profile.password.edit');
		Route::patch('/password', 'ProfileController@change_password')->name('profile.password.change');
		Route::resource('/admins', 'AdminController');

		Route::get('/settings', 'SettingsController@edit')->name('board.settings.edit');
		Route::patch('/settings', 'SettingsController@update')->name('board.settings.update');

		// Route::resource('/customers', 'CustomerController');

		Route::resource('/building_types', 'BuildingTypeController');
		// Route::get('/')
		Route::post('/admins/change_status', 'AdminController@change_status');
		Route::post('/drivers/change_status', 'DriverController@change_status');
		Route::get('/drivers/reports', 'DriverController@reports')->name('drivers.reports');
		Route::get('/drivers/bonus', 'DriverController@bonus')->name('drivers.bonus');
		Route::get('/drivers/{driver}/bills', 'DriverController@driver_bills')->name('drivers.bills');
		Route::get('/drivers/{driver}/trips', 'DriverController@driver_trips')->name('drivers.trips');
		Route::get('/drivers/track'  , 'BoardController@track_drivers_on_map' )->name('track_drivers');
		Route::get('/drivers/{driver}/track'  , 'DriverController@track_driver_on_map' )->name('drivers.track');

		Route::resource('/drivers', 'DriverController');	
		Route::resource('/markets', 'MarketController');
		Route::resource('/discounts', 'DiscountController');
		Route::resource('/trips', 'TripController');
		Route::resource('/cities', 'CityController');
		Route::resource('/governorates', 'GovernorateController');
		Route::resource('/city_delivery_prices', 'CityDeliveryPriceController');
		Route::resource('/push_notifications', 'PushNotificationController');
		Route::resource('/admin_types', 'AdminTypeController');
		Route::resource('/customers', 'CustomerController');
		Route::get('/governorates/{governorate}/delivery_prices/create', 'GovernorateController@delivery_prices_create')->name('governorates.delivery_prices.create');
		Route::post('/governorates/{governorate}/delivery_prices', 'GovernorateController@delivery_prices_store')->name('governorates.delivery_prices.store');
		Route::get('/governorates/{governorate}/delivery_prices/', 'GovernorateController@delivery_prices')->name('governorates.delivery_prices.index');
		Route::get('/markets/{market}/admin', 'MarketController@admin')->name('market.admin');
		Route::get('/markets/{market}/branches', 'MarketController@branches')->name('market.branches.index');
		Route::get('/markets/{market}/trips', 'MarketController@trips')->name('market.trips');
		Route::get('/markets/{market}/documents', 'MarketController@documents')->name('market.documents');
		Route::get('/markets/{market}/emails', 'MarketController@emails')->name('market.emails');
		Route::get('/markets/{market}/bank_accounts', 'MarketController@bank_accounts')->name('market.bank_accounts');
		Route::get('/markets/{market}/delivery_prices', 'MarketController@delivery_prices')->name('market.delivery_prices');
		Route::get('/market_documents/{file}/download', 'MarketDocumentController@download')->name('market.documents.download');
		Route::get('/markets/{market}/statistics', 'MarketController@statistics')->name('market.statistics');

		Route::get('/markets/{market}/delivery_prices/create', 'MarketController@add_delivery_prices')
			->name('market.delivery_prices.create');
		Route::post('/markets/{market}/delivery_prices', 'MarketController@store_delivery_prices')
			->name('market.delivery_prices.store');
		Route::delete('/delivery_prices/{delivery_price}', 'DeliveryPriceController@destroy')->name('delivery_prices.destroy');
		Route::get('/delivery_prices/{delivery_price}/edit', 'DeliveryPriceController@edit')->name('delivery_prices.edit');
		Route::patch('/delivery_prices/{delivery_price}', 'DeliveryPriceController@update')->name('delivery_prices.update');
		Route::get('/searching_cities', 'CityController@ajax_search');
		Route::get('/search_in_cities', 'CityController@search_in_cities');
		Route::get('/get_governorate_cities', 'CityController@get_governorate_cities');
		Route::get('/get_cities_we_can_set_price_to_it', 'CityDeliveryPriceController@get_cities_we_can_set_price_to_it');
		//ajax request
		Route::get('/ajax/search_markets', 'MarketController@ajax_search');
		Route::get('/ajax/search_branches', 'BranchController@get_market_branches_via_ajax');
		Route::get('/ajax/search_customers', 'CustomerController@ajax_search_customers');
		Route::get('/ajax/search_drivers', 'DriverController@search_drivers');
		Route::get('/markets_get_city_delivery_price_row', 'MarketController@get_city_delivery_price_row');
		Route::get('/available_cities_to_add_to_this_market', 'MarketController@available_cities_to_add_to_this_market');
		Route::delete('ajax/delete_delivery_price', 'CityDeliveryPriceController@ajax_delete');
		Route::delete('ajax/delete_admin_type', 'AdminTypeController@ajax_delete');
		Route::delete('ajax/delete_bill_type', 'BillTypeController@ajax_delete');

		Route::get('/get_governorate_cities', 'AjaxController@get_governorate_cities');
		Route::post('/save_customer'  , 'AjaxController@add_new_customar_via_ajax' );
		Route::get('/admins_notifications/create'   , 'AdminNotificationController@create' )->name('admins_notifications.create');
		Route::post('/admins_notifications'   , 'AdminNotificationController@store' )->name('admins_notifications.store');
		Route::get('/markets_notifications/create'   , 'MerchantNotificationController@create' )->name('markets_notifications.create');
		Route::post('/markets_notifications'   , 'MerchantNotificationController@store' )->name('markets_notifications.store');
		Route::get('/notifications'  , 'ProfileController@notifications');
		Route::get('/bills'  , 'BillController@index' )->name('bills.index');
		Route::get('/bills/{bill}'  , 'BillController@show' )->name('bills.show');
		Route::get('/bills/{bill}/print'  , 'BillController@print' )->name('bills.print');

		Route::get('/bills/{bill}/refuse'  , 'BillController@refuse' )->name('bills.refuse');
		Route::get('/bills/{bill}/accept'  , 'BillController@accept' )->name('bills.accept');


		Route::resource('/bill_types' , 'BillTypeController');
		Route::get('/markets/{market}/branches/create'  , 'BranchController@create' )->name('market.branches.create');
		Route::post('/markets/{market}/branches'  , 'BranchController@store' )->name('market.branches.store');
		Route::get('/markets/{market}/branches/{branch}/edit'  , 'BranchController@edit' )->name('market.branches.edit');
		Route::patch('/markets/{market}/branches/{branch}'  , 'BranchController@update' )->name('market.branches.update');
		Route::get('/markets/{market}/branches/{branch}'  , 'BranchController@show' )->name('market.branches.show');
		Route::delete('/markets/{market}/branches/{branch}' , 'BranchController@destroy')->name('market.branches.destroy');




	});
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/Board/login', 'Board\Auth\LoginController@login_form')->name('Board.login_form');
Route::post('/Board/login', 'Board\Auth\LoginController@login')->name('Board.login');

app/Http/Controllers/Board/AdminController.php
<?php

namespace App\Http\Controllers\Board;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Admin;
use App\Models\PermissionGroup;
use App\Models\AdminPermission;
use App\Models\AdminType;
use App\Http\Requests\Admins\StoreAdminRequest;
use App\Http\Requests\Admins\UpdateAdminRequest;
use Auth;
use Storage;
class AdminController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        $admins = Admin::withCount('dailyTrips')->latest()->get();
        return view('board.admins.index' , compact('admins'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $groups = PermissionGroup::with('permissions')->get();  
        $types = AdminType::where('active' , 1)->get();
        return view('board.admins.create' , compact('groups' , 'types'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreAdminRequest $request)
    {
        $admin = new Admin;

        if (!$admin->add($request->all())) 
            return back()->with('error_msg'  , trans('admins.adding_error') );


        if ($request->hasFile('profile_picture')) {
            $path = $request->file('profile_picture')->store('admins', 's3');
            $admin->setImage(basename($path));
        }

        
        if ($request->permissions != null) {
            $current_logged_in_admin_id = Auth::guard('admin')->id();
            $permissions = [] ;
            foreach ($request->permissions as $permission) {
                $permissions[] = new AdminPermission([
                    'permission_id' => $permission ,
                    'added_by' => $current_logged_in_admin_id,
                ]);
            }

            $admin->permissions()->saveMany($permissions);
        }



        return redirect(route('admins.index'))->with('success_msg'  , trans('admins.adding_success') );
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Admin $admin)
    {
        $admin->load(['permissions.permission'  , 'addedBy' ]);
        return view('board.admins.admin'  , compact('admin') );
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Admin $admin)
    {
        $groups = PermissionGroup::with('permissions')->get(); 
        $types = AdminType::where('active' , 1)->get();
        $admin->load('permissions');
        $admin_permissions = $admin->permissions()->pluck('permission_id')->toArray();

        return view('board.admins.edit'  , compact('admin' , 'groups' , 'admin_permissions' , 'types') );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateAdminRequest $request,Admin $admin)
    {
        if (!$admin->edit($request->all())) 
            return back()->with('error_msg'  , trans('admins.adding_error') );


        if ($request->hasFile('profile_picture')) {
            $path = $request->file('profile_picture')->store('admins', 's3');
            $admin->setImage(basename($path));
        }


        $admin->permissions()->delete();

        if ($request->permissions != null) {
            $current_logged_in_admin_id = Auth::guard('admin')->id();
            $permissions = [] ;
            foreach ($request->permissions as $permission) {
                $permissions[] = new AdminPermission([
                    'permission_id' => $permission ,
                    'added_by' => $current_logged_in_admin_id,
                ]);
            }

            $admin->permissions()->saveMany($permissions);
        }
        


        return back()->with('success_msg'  , trans('admins.updating_success') );

        

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Admin $admin)
    {
        if($admin->remove())
            return redirect(route('admins.index'))->with('success_msg' , trans('admins.deleted_success') );
    }


    public function change_status(Request $request)
    {
        $admin = Admin::find($request->admin_id);

        if ($admin) {
            $admin->active = $request->status;
            $admin->save();
        }

    }
}

app/Http/Controllers/Board/AdminNotificationController.php
<?php

namespace App\Http\Controllers\Board;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Admin;
use Auth;
use App\Models\AdminNotification;
use App\Http\Requests\Board\AdminNotification\StoreAdminNotificationRequest;
class AdminNotificationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $admins = Admin::with('type')->get();
        return view('board.admins_notifications.create' , compact('admins'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreAdminNotificationRequest $request)
    {


        if(in_array('all', $request->admins))
            $admins = Admin::pluck('id')->toArray();
        else
            $admins = $request->admins;


        $notifications = [];


        foreach ($admins as $admin) {
            $notifications[] = [
                'title_ar' => $request->title_ar,
                'content_ar' => $request->content_ar,
                'content_en' => $request->content_en,
                'title_en' => $request->title_en,
                'seen' => 0 , 
                'added_by' => Auth::guard('admin')->id() , 
                'admin_id' => $admin , 
                'created_at' => now()
            ];
        }

        AdminNotification::insert($notifications);


        return back()->with('success_msg'  , trans('admins.notification_send_successfully') );

    }
}

app/Http/Controllers/Board/AdminTypeController.php
<?php

namespace App\Http\Controllers\Board;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\StoreAdminTypeRequest;
use App\Http\Requests\UpdateAdminTypeRequest;

use App\Models\AdminType;

class AdminTypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $types = AdminType::latest()->get();
        return view('board.admin_types.index'  , compact('types') );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('board.admin_types.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreAdminTypeRequest $request)
    {
        $type = new AdminType;
        if($type->add($request->all()))
            return redirect(route('admin_types.index'))->with('success_msg'  , trans('admin_types.success_add'));

        return back()->with('success_msg'  , trans('admin_types.error_add'));              
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(AdminType $admin_type)
    {
        return view('board.admin_types.edit'  , compact('admin_type') );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateAdminTypeRequest $request, AdminType $admin_type)
    {
         if($admin_type->edit($request->all()))
            return redirect(route('admin_types.index'))->with('success_msg'  , trans('admin_types.success_edit'));

        return back()->with('success_msg'  , trans('admin_types.error_edit')); 
    }


    public function ajax_delete(Request $request)
    {
        $type = AdminType::find($request->id);
    
        $type->delete();


        return response()->json( ['status' => 'success' , 'msg' => trans('admin_types.deleted_success') ]  , 200);
    }

    
}

resources/views/board/markets/market_bank_accounts.blade.php
@php
$lang = session()->get('locale');
@endphp
@extends('board.layout.master')
@section('title')
@lang('markets.market_details')
@endsection


@section('header')
<div class="page-header ">
	<div class="page-header-content header-elements-md-inline">
		<div class="page-title d-flex">
			<h4><i class="icon-arrow-right6 mr-2"></i> @lang('markets.markets') </h4>
			<a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
		</div>
		<div class="header-elements d-none py-0 mb-3 mb-md-0">
			<div class="breadcrumb">
				<a href="{{ route('board.index') }}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i>  @lang('board.board') </a>
				<a href="{{ route('markets.index') }}" class="breadcrumb-item"><i class="icon-users4 mr-2"></i>  @lang('markets.markets') </a>
				<span class="breadcrumb-item active"> @lang('markets.market_details') </span>
			</div>
		</div>
	</div>
</div>
@endsection

@section('content')

<div class="row">

	<div class="col-md-12 mb-3">
		<div class="header-elements ">
			<div class="float-right">
				<a href="{{ route('markets.create') }}" class="btn btn-primary ml-1"> <i class="icon-user-plus"></i> @lang('markets.add_new_market')  </a>
				<a href="{{ route('markets.edit'  , ['market' => $market->id ] ) }}" class="btn btn-warning ml-1"> <i class="icon-pencil5"></i> @lang('markets.edit_market_details')  </a>
				<form action="{{ route('markets.destroy'  , ['market' => $market->id] ) }}" method="POST" class="float-right ml-1">
					@csrf
					@method('DELETE')
					<button class="btn btn-danger "> <i class="icon-trash"></i> @lang('markets.delete_market') </button>
				</form>
			</div>
		</div>
	</div>


	@include('board.layout.messages')

	<div class="col-md-2">
		<div class="card">
			<div class="card-body text-center">
				<div class="card-img-actions d-inline-block mb-3">
					<img class="img-thumbnail img-responsive " src="{{ Storage::disk('s3')->url('markets/'.$market->logo) }}" alt="" width="170" height="170">
				</div>
				<h6 class="font-weight-semibold mb-0">{{ $market->name }}</h6>
			</div>
		</div>
		

		<div class="card">
			<div class="list-group list-group-flush ">
				<a href="{{ route('markets.show'  , ['market' => $market->id] ) }}" class="list-group-item list-group-item-action  text-dark ">
					<i class="icon-store mr-3"></i>
					@lang('markets.market_details')
				</a>
				<a href="{{ route('market.admin'  , ['market' => $market->id ] ) }}" class="list-group-item list-group-item-action text-dark ">
					<i class="icon-user mr-3"></i>
					@lang('markets.market_admin')
				</a>
				<a href="{{ route('market.branches.index'  , ['market' => $market->id ] ) }}" class="list-group-item list-group-item-action text-dark">
					<i class="icon-git-branch  mr-3"></i>
					@lang('markets.branches')
				</a>
				<a href="{{ route('market.documents'  , ['market' => $market->id ] ) }}" class="list-group-item list-group-item-action text-dark">
					<i class="icon-files-empty  mr-3"></i>
					@lang('markets.documents')
				</a>
				<a href="{{ route('market.trips'  , ['market' => $market->id ] ) }}" class="list-group-item list-group-item-action text-dark">
					<i class="icon-location3  mr-3"></i>
					@lang('markets.trips')
				</a>
				<a href="{{ route('market.bank_accounts'  , ['market' => $market->id ] ) }}" class="list-group-item list-group-item-action text-white active">
					<i class="icon-coin-dollar  mr-3"></i>
					@lang('markets.bank_accounts')
				</a>
				<a href="{{ route('market.emails'  , ['market' => $market->id ] ) }}" class="list-group-item list-group-item-action text-dark">
					<i class="icon-mail-read  mr-3"></i>
					@lang('markets.emails')
				</a>
				<a href="{{ route('market.delivery_prices'  , ['market' => $market->id ] ) }}" class="list-group-item list-group-item-action text-dark">
					<i class="icon-coin-dollar  mr-3"></i>
					@lang('markets.delivery_prices')
				</a>
				<a href="{{ route('market.statistics'  , ['market' => $market->id ] ) }}" class="list-group-item list-group-item-action  text-dark">
					<i class="icon-coin-dollar  mr-3"></i>
					@lang('markets.statistics')
				</a>
			</div>
		</div>
	</div>
	<div class="col-md-10">
		<!-- Account settings -->
		
		@foreach ($market->bank_accounts as $bank_account)
		<div class="card card-body">
			<div class="media align-items-center align-items-lg-start text-center text-lg-left flex-column flex-lg-row">

				<div class="media-body">
					<h6 class="media-title font-weight-semibold">
						@lang('markets.bank_name') : {{ $bank_account->bank_name }}
					</h6>

					<ul class="list-inline list-inline-dotted mb-3 mb-lg-2">
						<li class="list-inline-item"> @lang('markets.account_owner_name') : {{ $bank_account->account_owner_name }}  </li>
					</ul>

					<p class="mb-3"> {{ $bank_account->notes }} </p>

					<ul class="list-inline list-inline-dotted mb-0">
						<li class="list-inline-item"> @lang('markets.added_by') <a target="_blank" href="{{ route('admins.show'  , ['admin' => $bank_account->admin_id ] ) }}"> {{ optional($bank_account->admin)->username }}</a></li>
						<li class="list-inline-item"> @lang('markets.created_at')  <span  class="text-muted" >  {{ $bank_account->created_at->toFormattedDateString() }} - {{ $bank_account->created_at->diffForHumans() }} </span> </li>
					</ul>
				</div>

				<div class="mt-3 mt-lg-0 ml-lg-3 text-center">
					<h3 class="mb-0 font-weight-semibold">{{ $bank_account->bank_account_number }}</h3>

					<div class="text-dark"> {{ $bank_account->swift_code }} </div>

					<button type="button" class="btn bg-warning-400 mt-3 btn-sm"><i class="icon-pencil5 mr-2"></i> @lang('markets.edit') </button>
					<button type="button" class="btn bg-danger-400 mt-3 btn-sm"><i class="icon-trash  mr-2"></i> @lang('markets.delete') </button>
				</div>
			</div>
		</div>
		@endforeach

	</div>
</div>

@endsection


@section('styles')

@endsection

@section('scripts')

@endsection

resources/views/board/markets/market_statistics.blade.php
@php
$lang = session()->get('locale');
@endphp
@extends('board.layout.master')
@section('title')
@lang('markets.market_details')
@endsection


@section('header')
<div class="page-header ">
	<div class="page-header-content header-elements-md-inline">
		<div class="page-title d-flex">
			<h4><i class="icon-arrow-right6 mr-2"></i> @lang('markets.markets') </h4>
			<a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
		</div>
		<div class="header-elements d-none py-0 mb-3 mb-md-0">
			<div class="breadcrumb">
				<a href="{{ route('board.index') }}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i>  @lang('board.board') </a>
				<a href="{{ route('markets.index') }}" class="breadcrumb-item"><i class="icon-users4 mr-2"></i>  @lang('markets.markets') </a>
				<span class="breadcrumb-item active"> @lang('markets.market_details') </span>
			</div>
		</div>
	</div>
</div>
@endsection

@section('content')

<div class="row">

	<div class="col-md-12 mb-3">
		<div class="header-elements ">
			<div class="float-right">
				<a href="{{ route('markets.create') }}" class="btn btn-primary ml-1"> <i class="icon-user-plus"></i> @lang('markets.add_new_market')  </a>
				<a href="{{ route('markets.edit'  , ['market' => $market->id ] ) }}" class="btn btn-warning ml-1"> <i class="icon-pencil5"></i> @lang('markets.edit_market_details')  </a>
				<form action="{{ route('markets.destroy'  , ['market' => $market->id] ) }}" method="POST" class="float-right ml-1">
					@csrf
					@method('DELETE')
					<button class="btn btn-danger "> <i class="icon-trash"></i> @lang('markets.delete_market') </button>
				</form>
			</div>
		</div>
	</div>


	@include('board.layout.messages')

	<div class="col-md-2">
		<div class="card">
			<div class="card-body text-center">
				<div class="card-img-actions d-inline-block mb-3">
					<img class="img-thumbnail img-responsive " src="{{ Storage::disk('s3')->url('markets/'.$market->logo) }}" alt="" width="170" height="170">
				</div>
				<h6 class="font-weight-semibold mb-0">{{ $market->name }}</h6>
			</div>
		</div>
		

		<div class="card">
			<div class="list-group list-group-flush ">
				<a href="{{ route('markets.show'  , ['market' => $market->id] ) }}" class="list-group-item list-group-item-action  text-dark ">
					<i class="icon-store mr-3"></i>
					@lang('markets.market_details')
				</a>
				<a href="{{ route('market.admin'  , ['market' => $market->id ] ) }}" class="list-group-item list-group-item-action text-dark ">
					<i class="icon-user mr-3"></i>
					@lang('markets.market_admin')
				</a>
				<a href="{{ route('market.branches.index'  , ['market' => $market->id ] ) }}" class="list-group-item list-group-item-action text-dark">
					<i class="icon-git-branch  mr-3"></i>
					@lang('markets.branches')
				</a>
				<a href="{{ route('market.documents'  , ['market' => $market->id ] ) }}" class="list-group-item list-group-item-action text-dark">
					<i class="icon-files-empty  mr-3"></i>
					@lang('markets.documents')
				</a>
				<a href="{{ route('market.trips'  , ['market' => $market->id ] ) }}" class="list-group-item list-group-item-action text-dark">
					<i class="icon-location3  mr-3"></i>
					@lang('markets.trips')
				</a>
				<a href="{{ route('market.bank_accounts'  , ['market' => $market->id ] ) }}" class="list-group-item list-group-item-action text-dark">
					<i class="icon-coin-dollar  mr-3"></i>
					@lang('markets.bank_accounts')
				</a>
				<a href="{{ route('market.emails'  , ['market' => $market->id ] ) }}" class="list-group-item list-group-item-action text-dark">
					<i class="icon-mail-read  mr-3"></i>
					@lang('markets.emails')
				</a>
				<a href="{{ route('market.delivery_prices'  , ['market' => $market->id ] ) }}" class="list-group-item list-group-item-action text-dark">
					<i class="icon-coin-dollar  mr-3"></i>
					@lang('markets.delivery_prices')
				</a>
				<a href="{{ route('market.statistics'  , ['market' => $market->id ] ) }}" class="list-group-item list-group-item-action active text-white">
					<i class="icon-coin-dollar  mr-3"></i>
					@lang('markets.statistics')
				</a>
			</div>
		</div>
	</div>
	<div class="col-md-10">
		<livewire:market-statistics />
	</div>
</div>

@endsection


@section('styles')

@endsection

@section('scripts')
<script src="{{ asset('board_assets/global_assets/js/demo_charts/pages/dashboard/light/heatmaps.js') }}"></script>
<script src="{{ asset('board_assets/global_assets/js/demo_charts/pages/dashboard/light/pies.js') }}"></script>
<script src="{{ asset('board_assets/global_assets/js/demo_charts/pages/dashboard/light/bullets.js') }}"></script>
<script src="{{ asset('board_assets/global_assets/js/demo_pages/dashboard.js') }}"></script>

@endsection