routes/web.php
<?php

use Illuminate\Support\Facades\Route;
require_once 'merchant-routes.php';
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::group(['prefix' => 'Board', 'middleware' => ['admin', 'lang'], 'namespace' => 'Board'],

function () {
		Route::get('/', 'BoardController@index')->name('board.index');
		Route::get('/language/{lang}', 'BoardController@change_language')->name('board.lang');
		Route::get('/logout', 'Auth\LoginController@logout')->name('board.logout');
		Route::get('/profile', 'ProfileController@index')->name('board.profile');
		Route::patch('/profile', 'ProfileController@update')->name('board.profile.update');
		Route::get('/password', 'ProfileController@edit_password')->name('profile.password.edit');
		Route::patch('/password', 'ProfileController@change_password')->name('profile.password.change');
		Route::resource('/admins', 'AdminController');

		Route::get('/settings', 'SettingsController@edit')->name('board.settings.edit');
		Route::patch('/settings', 'SettingsController@update')->name('board.settings.update');

		// Route::resource('/customers', 'CustomerController');

		Route::resource('/building_types', 'BuildingTypeController');
		// Route::get('/')
		Route::post('/admins/change_status', 'AdminController@change_status');
		Route::post('/drivers/change_status', 'DriverController@change_status');
		Route::get('/drivers/reports', 'DriverController@reports')->name('drivers.reports');
		Route::get('/drivers/bonus', 'DriverController@bonus')->name('drivers.bonus');
		Route::get('/drivers/{driver}/bills', 'DriverController@driver_bills')->name('drivers.bills');
		Route::get('/drivers/{driver}/trips', 'DriverController@driver_trips')->name('drivers.trips');
		Route::get('/drivers/track'  , 'BoardController@track_drivers_on_map' )->name('track_drivers');
		Route::get('/drivers/{driver}/track'  , 'DriverController@track_driver_on_map' )->name('drivers.track');

		Route::resource('/drivers', 'DriverController');	
		Route::resource('/markets', 'MarketController');
		Route::resource('/discounts', 'DiscountController');
		Route::resource('/trips', 'TripController');
		Route::resource('/cities', 'CityController');
		Route::resource('/governorates', 'GovernorateController');
		Route::resource('/city_delivery_prices', 'CityDeliveryPriceController');
		Route::resource('/push_notifications', 'PushNotificationController');
		Route::resource('/admin_types', 'AdminTypeController');
		Route::resource('/customers', 'CustomerController');
		Route::get('/governorates/{governorate}/delivery_prices/create', 'GovernorateController@delivery_prices_create')->name('governorates.delivery_prices.create');
		Route::post('/governorates/{governorate}/delivery_prices', 'GovernorateController@delivery_prices_store')->name('governorates.delivery_prices.store');
		Route::get('/governorates/{governorate}/delivery_prices/', 'GovernorateController@delivery_prices')->name('governorates.delivery_prices.index');
		Route::get('/markets/{market}/admin', 'MarketController@admin')->name('market.admin');
		Route::get('/markets/{market}/branches', 'MarketController@branches')->name('market.branches.index');
		Route::get('/markets/{market}/trips', 'MarketController@trips')->name('market.trips');
		Route::get('/markets/{market}/documents', 'MarketController@documents')->name('market.documents');
		Route::get('/markets/{market}/emails', 'MarketController@emails')->name('market.emails');
		Route::get('/markets/{market}/bank_accounts', 'MarketController@bank_accounts')->name('market.bank_accounts');
		Route::get('/markets/{market}/delivery_prices', 'MarketController@delivery_prices')->name('market.delivery_prices');
		Route::get('/market_documents/{file}/download', 'MarketDocumentController@download')->name('market.documents.download');
		Route::get('/markets/{market}/statistics', 'MarketController@statistics')->name('market.statistics');

		Route::get('/markets/{market}/delivery_prices/create', 'MarketController@add_delivery_prices')
			->name('market.delivery_prices.create');
		Route::post('/markets/{market}/delivery_prices', 'MarketController@store_delivery_prices')
			->name('market.delivery_prices.store');
		Route::delete('/delivery_prices/{delivery_price}', 'DeliveryPriceController@destroy')->name('delivery_prices.destroy');
		Route::get('/delivery_prices/{delivery_price}/edit', 'DeliveryPriceController@edit')->name('delivery_prices.edit');
		Route::patch('/delivery_prices/{delivery_price}', 'DeliveryPriceController@update')->name('delivery_prices.update');
		Route::get('/searching_cities', 'CityController@ajax_search');
		Route::get('/search_in_cities', 'CityController@search_in_cities');
		Route::get('/get_governorate_cities', 'CityController@get_governorate_cities');
		Route::get('/get_cities_we_can_set_price_to_it', 'CityDeliveryPriceController@get_cities_we_can_set_price_to_it');
		//ajax request
		Route::get('/ajax/search_markets', 'MarketController@ajax_search');
		Route::get('/ajax/search_branches', 'BranchController@get_market_branches_via_ajax');
		Route::get('/ajax/search_customers', 'CustomerController@ajax_search_customers');
		Route::get('/ajax/search_drivers', 'DriverController@search_drivers');
		Route::get('/markets_get_city_delivery_price_row', 'MarketController@get_city_delivery_price_row');
		Route::get('/available_cities_to_add_to_this_market', 'MarketController@available_cities_to_add_to_this_market');
		Route::delete('ajax/delete_delivery_price', 'CityDeliveryPriceController@ajax_delete');
		Route::delete('ajax/delete_admin_type', 'AdminTypeController@ajax_delete');
		Route::delete('ajax/delete_bill_type', 'BillTypeController@ajax_delete');

		Route::get('/get_governorate_cities', 'AjaxController@get_governorate_cities');
		Route::post('/save_customer'  , 'AjaxController@add_new_customar_via_ajax' );
		Route::get('/admins_notifications/create'   , 'AdminNotificationController@create' )->name('admins_notifications.create');
		Route::post('/admins_notifications'   , 'AdminNotificationController@store' )->name('admins_notifications.store');
		Route::get('/markets_notifications/create'   , 'MerchantNotificationController@create' )->name('markets_notifications.create');
		Route::post('/markets_notifications'   , 'MerchantNotificationController@store' )->name('markets_notifications.store');
		Route::get('/notifications'  , 'ProfileController@notifications');
		Route::get('/bills'  , 'BillController@index' )->name('bills.index');
		Route::get('/bills/{bill}'  , 'BillController@show' )->name('bills.show');
		Route::get('/bills/{bill}/print'  , 'BillController@print' )->name('bills.print');

		Route::get('/bills/{bill}/refuse'  , 'BillController@refuse' )->name('bills.refuse');
		Route::get('/bills/{bill}/accept'  , 'BillController@accept' )->name('bills.accept');


		Route::resource('/bill_types' , 'BillTypeController');
		Route::get('/markets/{market}/branches/create'  , 'BranchController@create' )->name('market.branches.create');
		Route::post('/markets/{market}/branches'  , 'BranchController@store' )->name('market.branches.store');
		Route::get('/markets/{market}/branches/{branch}/edit'  , 'BranchController@edit' )->name('market.branches.edit');
		Route::patch('/markets/{market}/branches/{branch}'  , 'BranchController@update' )->name('market.branches.update');
		Route::get('/markets/{market}/branches/{branch}'  , 'BranchController@show' )->name('market.branches.show');
		Route::delete('/markets/{market}/branches/{branch}' , 'BranchController@destroy')->name('market.branches.destroy');




	});
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/Board/login', 'Board\Auth\LoginController@login_form')->name('Board.login_form');
Route::post('/Board/login', 'Board\Auth\LoginController@login')->name('Board.login');

app/Http/Controllers/Board/AdminController.php
<?php

namespace App\Http\Controllers\Board;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Admin;
use App\Models\PermissionGroup;
use App\Models\AdminPermission;
use App\Models\AdminType;
use App\Http\Requests\Admins\StoreAdminRequest;
use App\Http\Requests\Admins\UpdateAdminRequest;
use Auth;
use Storage;
class AdminController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        $admins = Admin::withCount('dailyTrips')->latest()->get();
        return view('board.admins.index' , compact('admins'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $groups = PermissionGroup::with('permissions')->get();  
        $types = AdminType::where('active' , 1)->get();
        return view('board.admins.create' , compact('groups' , 'types'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreAdminRequest $request)
    {
        $admin = new Admin;

        if (!$admin->add($request->all())) 
            return back()->with('error_msg'  , trans('admins.adding_error') );


        if ($request->hasFile('profile_picture')) {
            $path = $request->file('profile_picture')->store('admins', 's3');
            $admin->setImage(basename($path));
        }

        
        if ($request->permissions != null) {
            $current_logged_in_admin_id = Auth::guard('admin')->id();
            $permissions = [] ;
            foreach ($request->permissions as $permission) {
                $permissions[] = new AdminPermission([
                    'permission_id' => $permission ,
                    'added_by' => $current_logged_in_admin_id,
                ]);
            }

            $admin->permissions()->saveMany($permissions);
        }



        return redirect(route('admins.index'))->with('success_msg'  , trans('admins.adding_success') );
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Admin $admin)
    {
        $admin->load(['permissions.permission'  , 'addedBy' ]);
        return view('board.admins.admin'  , compact('admin') );
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Admin $admin)
    {
        $groups = PermissionGroup::with('permissions')->get(); 
        $types = AdminType::where('active' , 1)->get();
        $admin->load('permissions');
        $admin_permissions = $admin->permissions()->pluck('permission_id')->toArray();

        return view('board.admins.edit'  , compact('admin' , 'groups' , 'admin_permissions' , 'types') );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateAdminRequest $request,Admin $admin)
    {
        if (!$admin->edit($request->all())) 
            return back()->with('error_msg'  , trans('admins.adding_error') );


        if ($request->hasFile('profile_picture')) {
            $path = $request->file('profile_picture')->store('admins', 's3');
            $admin->setImage(basename($path));
        }


        $admin->permissions()->delete();

        if ($request->permissions != null) {
            $current_logged_in_admin_id = Auth::guard('admin')->id();
            $permissions = [] ;
            foreach ($request->permissions as $permission) {
                $permissions[] = new AdminPermission([
                    'permission_id' => $permission ,
                    'added_by' => $current_logged_in_admin_id,
                ]);
            }

            $admin->permissions()->saveMany($permissions);
        }
        


        return back()->with('success_msg'  , trans('admins.updating_success') );

        

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Admin $admin)
    {
        if($admin->remove())
            return redirect(route('admins.index'))->with('success_msg' , trans('admins.deleted_success') );
    }


    public function change_status(Request $request)
    {
        $admin = Admin::find($request->admin_id);

        if ($admin) {
            $admin->active = $request->status;
            $admin->save();
        }

    }
}

app/Http/Controllers/Board/AdminNotificationController.php
<?php

namespace App\Http\Controllers\Board;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Admin;
use Auth;
use App\Models\AdminNotification;
use App\Http\Requests\Board\AdminNotification\StoreAdminNotificationRequest;
class AdminNotificationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $admins = Admin::with('type')->get();
        return view('board.admins_notifications.create' , compact('admins'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreAdminNotificationRequest $request)
    {


        if(in_array('all', $request->admins))
            $admins = Admin::pluck('id')->toArray();
        else
            $admins = $request->admins;


        $notifications = [];


        foreach ($admins as $admin) {
            $notifications[] = [
                'title_ar' => $request->title_ar,
                'content_ar' => $request->content_ar,
                'content_en' => $request->content_en,
                'title_en' => $request->title_en,
                'seen' => 0 , 
                'added_by' => Auth::guard('admin')->id() , 
                'admin_id' => $admin , 
                'created_at' => now()
            ];
        }

        AdminNotification::insert($notifications);


        return back()->with('success_msg'  , trans('admins.notification_send_successfully') );

    }
}

app/Http/Controllers/Board/AdminTypeController.php
<?php

namespace App\Http\Controllers\Board;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\StoreAdminTypeRequest;
use App\Http\Requests\UpdateAdminTypeRequest;

use App\Models\AdminType;

class AdminTypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $types = AdminType::latest()->get();
        return view('board.admin_types.index'  , compact('types') );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('board.admin_types.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreAdminTypeRequest $request)
    {
        $type = new AdminType;
        if($type->add($request->all()))
            return redirect(route('admin_types.index'))->with('success_msg'  , trans('admin_types.success_add'));

        return back()->with('success_msg'  , trans('admin_types.error_add'));              
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(AdminType $admin_type)
    {
        return view('board.admin_types.edit'  , compact('admin_type') );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateAdminTypeRequest $request, AdminType $admin_type)
    {
         if($admin_type->edit($request->all()))
            return redirect(route('admin_types.index'))->with('success_msg'  , trans('admin_types.success_edit'));

        return back()->with('success_msg'  , trans('admin_types.error_edit')); 
    }


    public function ajax_delete(Request $request)
    {
        $type = AdminType::find($request->id);
    
        $type->delete();


        return response()->json( ['status' => 'success' , 'msg' => trans('admin_types.deleted_success') ]  , 200);
    }

    
}

resources/views/board/trips/index.blade.php
@php
$lang = session()->get('locale');
@endphp
@extends('board.layout.master')
@section('title')
@lang('trips.show_all_trips')
@endsection


@section('header')
<div class="page-header">
	<div class="page-header-content header-elements-md-inline">
		<div class="page-title d-flex">
			<h4><i class="icon-arrow-right6 mr-2"></i> @lang('trips.trips') </h4>
			<a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
		</div>
		<div class="header-elements d-none py-0 mb-3 mb-md-0">
			<div class="breadcrumb">
				<a href="{{ route('board.index') }}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i>  @lang('board.board') </a>
				<a href="{{ route('trips.index') }}" class="breadcrumb-item"><i class="icon-users4 mr-2"></i>  @lang('trips.trips') </a>
				<span class="breadcrumb-item active"> @lang('trips.show_all_trips') </span>
			</div>
		</div>
	</div>
</div>
@endsection

@section('content')

<div class="row">
	<div class="col-md-12">
		@include('board.layout.messages')
		
		<livewire:trips />
	</div>
</div>

@endsection


@section('styles')

@endsection

@section('scripts')

<script src="{{ asset('board_assets/global_assets/js/plugins/forms/styling/uniform.min.js') }}"></script>
<script src="{{ asset('board_assets/global_assets/js/demo_pages/content_cards_header.js') }}"></script>

@endsection

resources/views/board/trips/trip.blade.php
@php
$lang = session()->get('locale');
@endphp
@extends('board.layout.master')
@section('title')
@lang('trips.trip_details')
@endsection


@section('header')
<div class="page-header ">
	<div class="page-header-content header-elements-md-inline">
		<div class="page-title d-flex">
			<h4><i class="icon-arrow-right6 mr-2"></i> @lang('trips.trips') </h4>
			<a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
		</div>
		<div class="header-elements d-none py-0 mb-3 mb-md-0">
			<div class="breadcrumb">
				<a href="{{ route('board.index') }}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i>  @lang('board.board') </a>
				<a href="{{ route('trips.index') }}" class="breadcrumb-item"><i class="icon-users4 mr-2"></i>  @lang('trips.trips') </a>
				<span class="breadcrumb-item active"> @lang('trips.trip_details') </span>
			</div>
		</div>
	</div>
</div>
@endsection

@section('content')

<div class="row">
{{-- 
	<div class="col-md-12 mb-3">
		<div class="header-elements ">
			<div class="float-right">
				<a href="{{ route('trips.create') }}" class="btn btn-primary ml-1"> <i class="icon-user-plus"></i> @lang('trips.add_new_trip')  </a>
				<a href="{{ route('trips.edit'  , ['trip' => $trip->id ] ) }}" class="btn btn-warning ml-1"> <i class="icon-pencil5"></i> @lang('trips.edit_trip_details')  </a>
				<form action="{{ route('trips.destroy'  , ['trip' => $trip->id] ) }}" method="POST" class="float-right ml-1">
					@csrf
					@method('DELETE')
					<button href="#" class="btn btn-danger "> <i class="icon-trash"></i> @lang('trips.delete_trip') </button>
				</form>
			</div>
		</div>
	</div>
 --}}



	<div class="col-md-12">

		@include('board.layout.messages')
		<!-- Account settings -->
		<div class="card">
			<div class="card-header bg-dark header-elements-inline">
				<h5 class="card-title"> @lang('trips.trip_details') {{ $trip->username }} </h5>
				<div class="header-elements">
					<div class="list-icons">
						<a class="list-icons-item" data-action="collapse"></a>
						<a class="list-icons-item" data-action="reload"></a>
						<a class="list-icons-item" data-action="remove"></a>
					</div>
				</div>
			</div>

			<div class="card-body">
				<table class="table  table-xs border-top-0 my-2">
					<tbody>
						<tr>
							<th class="font-weight-bold text-dark">@lang('trips.trip_code')</th>
							<td class="text-left"> {{ $trip->code }} </td>
						</tr>
						<tr>
							<th class="font-weight-bold text-dark">@lang('trips.sender')</th>
							<td class="text-left"> 
								@if ($trip->sender_type == 'market')
								<a href="{{ route('markets.show' , ['market' => $trip->market_id ]  ) }}"> {{ optional($trip->market)->name }} </a>
								@else
								<a href="{{ route('customers.show' , ['customer' => $trip->market_id ]  ) }}"> {{ optional($trip->client)->name }} </a>
								@endif
							</td>
						</tr>
						<tr>
							<th class="font-weight-bold text-dark">@lang('trips.driver')</th>
							<td class="text-left"> 
								<a href="{{ route('drivers.show'  , ['driver' => $trip->driver_id] ) }}"> {{ optional($trip->driver)->name }} </a>
							</td>
						</tr>
						<tr>
							<th class="font-weight-bold text-dark">@lang('trips.order_price')</th>
							<td class="text-left"> {{ $trip->order_price }} </td>
						</tr>
						<tr>
							<th class="font-weight-bold text-dark">@lang('trips.delivery_price')</th>
							<td class="text-left"> {{ $trip->delivery_price }} </td>
						</tr>
						<tr>
							<th class="font-weight-bold text-dark">@lang('trips.delivery_date_to_customer')</th>
							<td class="text-left"> {{ $trip->delivery_date_to_customer->toDayDateTimeString() }} | <span class="text-muted" > {{  $trip->delivery_date_to_customer->diffForHumans() }} </span> </td>
						</tr>

						<tr>
							<th class="font-weight-bold text-dark">@lang('trips.receipt_date_from_market')</th>
							<td class="text-left"> {{ $trip->receipt_date_from_market->toDayDateTimeString() }} | <span class="text-muted">  {{ $trip->receipt_date_from_market->diffForHumans() }} </span> </td>
						</tr>
						<tr>
							<th class="font-weight-bold text-dark">@lang('trips.notes')</th>
							<td class="text-left"> {{ $trip->notes }} </td>
						</tr>
						<tr>
							<th class="font-weight-bold text-dark">@lang('trips.payment_method')</th>
							<td class="text-left"> {{ optional($trip->payment_method)['name_'.$lang] }} </td>
						</tr>

						<tr>
							<th class="font-weight-bold text-dark">@lang('trips.payment_status')</th>
							<td class="text-left"> 
								@switch($trip->paid)
								@case(0)
								<span class="badge bg-danger" > @lang('trips.paid') </span>
								@break
								@case(1)
								<span class="badge bg-success" > @lang('trips.unpaid') </span>
								@break
								@endswitch
								
							</td>
						</tr>

						<tr>
							<td class="font-weight-bold text-dark"> @lang('trips.status') </td>
							<td class="text-left"><span class="badge" style="background-color: {{ optional($trip->status)->color }};color: white" > {{ optional($trip->status)['name_'.$lang] }} </span> </td>
						</tr>


						<tr>
							<td class="font-weight-bold text-dark"> @lang('trips.created_at') </td>
							<td class="text-left"> {{ $trip->created_at->toFormattedDateString() }} - {{ $trip->created_at->diffForHumans() }} </td>
						</tr>

						<tr>
							<td class="font-weight-bold text-dark"> @lang('trips.notes') </td>
							<td class="text-left font-weight-bold"> {{ $trip->notes }} </td>
						</tr>

						<tr>
							<td class="font-weight-bold text-dark"> @lang('drivers.bounce') </td>
							<td class="text-left font-weight-bold"> {{ optional($trip->driver)->bounce }} </td>
						</tr>



						<tr>
							<td class="font-weight-semibold">  @lang('trips.order_image') </td>
							<td class="text-right text-muted">
								<img class="img-responsive img-thumbnail" width="300" height="300" src="{{ Storage::disk('s3')->url('trips/'.$trip->image) }}" alt="">
							</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
		<!-- /account settings -->
	</div>
</div>

@endsection


@section('styles')

@endsection

@section('scripts')
<script src="{{ asset('board_assets/global_assets/js/plugins/forms/styling/uniform.min.js') }}"></script>
<script src="{{ asset('board_assets/global_assets/js/plugins/forms/styling/switchery.min.js') }}"></script>
<script src="{{ asset('board_assets/global_assets/js/plugins/forms/styling/switch.min.js') }}"></script>
<script src="{{ asset('board_assets/global_assets/js/plugins/forms/selects/select2.min.js') }}"></script>
<script>
	$(function() {
		// $("#firstname").attr("disabled", "disabled");


		@if ($trip->type == 'supertrip')
		$('input.permissions').each(function(){
			$(this).prop('disabled',true);
			$.uniform.update();
		});
		@endif

		$('select[name="type"]').on('select2:select', function(event) {
			
			var trip_type = $(event.currentTarget).val();
			console.log(trip_type);
			if (trip_type == 'supertrip') {
				$('input.permissions').each(function(){
					console.log(trip_type);
					$(this).prop('disabled',true);
					$.uniform.update();
				});
			} else {
				$('input.permissions').each(function(){
					console.log(trip_type);
					$(this).prop('disabled',false);
					$.uniform.update();
				});
			}
		});


		$('.select').select2({
			minimumResultsForSearch: Infinity
		});

		$('.form-input-styled').uniform({
			fileButtonClass: 'action btn bg-primary'
		});


		var _componentSwitchery = function() {
			if (typeof Switchery == 'undefined') {
				console.warn('Warning - switchery.min.js is not loaded.');
				return;
			}


			var elems = Array.prototype.slice.call(document.querySelectorAll('.form-check-input-switchery'));
			elems.forEach(function(html) {
				var switchery = new Switchery(html);
			});

			var primary = document.querySelector('.form-check-input-switchery-primary');
			var switchery = new Switchery(primary, { color: '#2196F3' });
		};
    // Bootstrap switch
    var _componentBootstrapSwitch = function() {
    	if (!$().bootstrapSwitch) {
    		console.warn('Warning - switch.min.js is not loaded.');
    		return;
    	}

        // Initialize
        $('.form-check-input-switch').bootstrapSwitch();
    };
    _componentSwitchery();



});
</script>
@endsection