routes/web.php
<?php

use Illuminate\Support\Facades\Route;
require_once 'merchant-routes.php';
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::group(['prefix' => 'Board', 'middleware' => ['admin', 'lang'], 'namespace' => 'Board'],

function () {
		Route::get('/', 'BoardController@index')->name('board.index');
		Route::get('/language/{lang}', 'BoardController@change_language')->name('board.lang');
		Route::get('/logout', 'Auth\LoginController@logout')->name('board.logout');
		Route::get('/profile', 'ProfileController@index')->name('board.profile');
		Route::patch('/profile', 'ProfileController@update')->name('board.profile.update');
		Route::get('/password', 'ProfileController@edit_password')->name('profile.password.edit');
		Route::patch('/password', 'ProfileController@change_password')->name('profile.password.change');
		Route::resource('/admins', 'AdminController');

		Route::get('/settings', 'SettingsController@edit')->name('board.settings.edit');
		Route::patch('/settings', 'SettingsController@update')->name('board.settings.update');

		// Route::resource('/customers', 'CustomerController');

		Route::resource('/building_types', 'BuildingTypeController');
		// Route::get('/')
		Route::post('/admins/change_status', 'AdminController@change_status');
		Route::post('/drivers/change_status', 'DriverController@change_status');
		Route::get('/drivers/reports', 'DriverController@reports')->name('drivers.reports');
		Route::get('/drivers/bonus', 'DriverController@bonus')->name('drivers.bonus');
		Route::get('/drivers/{driver}/bills', 'DriverController@driver_bills')->name('drivers.bills');
		Route::get('/drivers/{driver}/trips', 'DriverController@driver_trips')->name('drivers.trips');
		Route::get('/drivers/track'  , 'BoardController@track_drivers_on_map' )->name('track_drivers');
		Route::get('/drivers/{driver}/track'  , 'DriverController@track_driver_on_map' )->name('drivers.track');

		Route::resource('/drivers', 'DriverController');	
		Route::resource('/markets', 'MarketController');
		Route::resource('/discounts', 'DiscountController');
		Route::resource('/trips', 'TripController');
		Route::resource('/cities', 'CityController');
		Route::resource('/governorates', 'GovernorateController');
		Route::resource('/city_delivery_prices', 'CityDeliveryPriceController');
		Route::resource('/push_notifications', 'PushNotificationController');
		Route::resource('/admin_types', 'AdminTypeController');
		Route::resource('/customers', 'CustomerController');
		Route::get('/governorates/{governorate}/delivery_prices/create', 'GovernorateController@delivery_prices_create')->name('governorates.delivery_prices.create');
		Route::post('/governorates/{governorate}/delivery_prices', 'GovernorateController@delivery_prices_store')->name('governorates.delivery_prices.store');
		Route::get('/governorates/{governorate}/delivery_prices/', 'GovernorateController@delivery_prices')->name('governorates.delivery_prices.index');
		Route::get('/markets/{market}/admin', 'MarketController@admin')->name('market.admin');
		Route::get('/markets/{market}/branches', 'MarketController@branches')->name('market.branches.index');
		Route::get('/markets/{market}/trips', 'MarketController@trips')->name('market.trips');
		Route::get('/markets/{market}/documents', 'MarketController@documents')->name('market.documents');
		Route::get('/markets/{market}/emails', 'MarketController@emails')->name('market.emails');
		Route::get('/markets/{market}/bank_accounts', 'MarketController@bank_accounts')->name('market.bank_accounts');
		Route::get('/markets/{market}/delivery_prices', 'MarketController@delivery_prices')->name('market.delivery_prices');
		Route::get('/market_documents/{file}/download', 'MarketDocumentController@download')->name('market.documents.download');
		Route::get('/markets/{market}/statistics', 'MarketController@statistics')->name('market.statistics');

		Route::get('/markets/{market}/delivery_prices/create', 'MarketController@add_delivery_prices')
			->name('market.delivery_prices.create');
		Route::post('/markets/{market}/delivery_prices', 'MarketController@store_delivery_prices')
			->name('market.delivery_prices.store');
		Route::delete('/delivery_prices/{delivery_price}', 'DeliveryPriceController@destroy')->name('delivery_prices.destroy');
		Route::get('/delivery_prices/{delivery_price}/edit', 'DeliveryPriceController@edit')->name('delivery_prices.edit');
		Route::patch('/delivery_prices/{delivery_price}', 'DeliveryPriceController@update')->name('delivery_prices.update');
		Route::get('/searching_cities', 'CityController@ajax_search');
		Route::get('/search_in_cities', 'CityController@search_in_cities');
		Route::get('/get_governorate_cities', 'CityController@get_governorate_cities');
		Route::get('/get_cities_we_can_set_price_to_it', 'CityDeliveryPriceController@get_cities_we_can_set_price_to_it');
		//ajax request
		Route::get('/ajax/search_markets', 'MarketController@ajax_search');
		Route::get('/ajax/search_branches', 'BranchController@get_market_branches_via_ajax');
		Route::get('/ajax/search_customers', 'CustomerController@ajax_search_customers');
		Route::get('/ajax/search_drivers', 'DriverController@search_drivers');
		Route::get('/markets_get_city_delivery_price_row', 'MarketController@get_city_delivery_price_row');
		Route::get('/available_cities_to_add_to_this_market', 'MarketController@available_cities_to_add_to_this_market');
		Route::delete('ajax/delete_delivery_price', 'CityDeliveryPriceController@ajax_delete');
		Route::delete('ajax/delete_admin_type', 'AdminTypeController@ajax_delete');
		Route::delete('ajax/delete_bill_type', 'BillTypeController@ajax_delete');

		Route::get('/get_governorate_cities', 'AjaxController@get_governorate_cities');
		Route::post('/save_customer'  , 'AjaxController@add_new_customar_via_ajax' );
		Route::get('/admins_notifications/create'   , 'AdminNotificationController@create' )->name('admins_notifications.create');
		Route::post('/admins_notifications'   , 'AdminNotificationController@store' )->name('admins_notifications.store');
		Route::get('/markets_notifications/create'   , 'MerchantNotificationController@create' )->name('markets_notifications.create');
		Route::post('/markets_notifications'   , 'MerchantNotificationController@store' )->name('markets_notifications.store');
		Route::get('/notifications'  , 'ProfileController@notifications');
		Route::get('/bills'  , 'BillController@index' )->name('bills.index');
		Route::get('/bills/{bill}'  , 'BillController@show' )->name('bills.show');
		Route::get('/bills/{bill}/print'  , 'BillController@print' )->name('bills.print');

		Route::get('/bills/{bill}/refuse'  , 'BillController@refuse' )->name('bills.refuse');
		Route::get('/bills/{bill}/accept'  , 'BillController@accept' )->name('bills.accept');


		Route::resource('/bill_types' , 'BillTypeController');
		Route::get('/markets/{market}/branches/create'  , 'BranchController@create' )->name('market.branches.create');
		Route::post('/markets/{market}/branches'  , 'BranchController@store' )->name('market.branches.store');
		Route::get('/markets/{market}/branches/{branch}/edit'  , 'BranchController@edit' )->name('market.branches.edit');
		Route::patch('/markets/{market}/branches/{branch}'  , 'BranchController@update' )->name('market.branches.update');
		Route::get('/markets/{market}/branches/{branch}'  , 'BranchController@show' )->name('market.branches.show');
		Route::delete('/markets/{market}/branches/{branch}' , 'BranchController@destroy')->name('market.branches.destroy');




	});
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/Board/login', 'Board\Auth\LoginController@login_form')->name('Board.login_form');
Route::post('/Board/login', 'Board\Auth\LoginController@login')->name('Board.login');

app/Http/Controllers/Board/TripController.php
<?php

namespace App\Http\Controllers\Board;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\City;
use App\Models\Trip;
use App\Models\Driver;
use App\Models\TripItem;
use App\Models\Governorate;
use App\Models\BuildingType;
use App\Models\PaymentMethod;
use App\Models\CustomerAddress;
use App\Models\TripStatus;
use App\Http\Requests\StoreTripRequest;
use PDF;
class TripController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        // $trips = Trip::all();

        // return PDF::loadView('board.drivers.pdf', compact('trips'))->download('trips.pdf');
        
        return view('board.trips.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $payment_methods = PaymentMethod::all();
        $governorates = Governorate::all();
        $building_types = BuildingType::all();
        $drivers = Driver::all();
        $clients = CustomerAddress::all();
        return view('board.trips.create' , compact('payment_methods' , 'governorates' ,  'building_types' , 'drivers'  , 'clients' ));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreTripRequest $request)
    {   

        // dd($request->all());
        foreach ($request->customers as $customer) {
            $trip = new Trip;
            $trip->add($request->all() , $customer);
            $items = [];
            for ($i = 0; $i <count($request->item_name) ; $i++) {
                if (!is_null($request->item_name[$i])) {
                    $items[] = new TripItem([
                        'name' => $request->item_name[$i],
                        'quantity' => $request->quantity[$i] , 
                        'trip_id' => $trip->id , 
                    ]);
                }
            }
           if(count($items))
                $trip->items()->saveMany($items);
        }

        // here we need to notify the diver about the order

        return redirect(route('trips.create'))->with('success_msg' , trans('trips.adding_success'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Trip $trip)
    {
        $trip->load(['market'  , 'client'  , 'address' , 'status' , 'payment_method' , 'branch' , 'driver' , 'status' ]);
        return view('board.trips.trip'  , compact('trip') );
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Merchant/AdminController.php
<?php

namespace App\Http\Controllers\Merchant;

use App\Http\Controllers\Controller;

use App\Http\Requests\Merchants\StoreAdminRequest;
use App\Models\AdminType;
use App\Models\Merchant;
use App\Models\MerchantPermission;
use App\Models\PermissionGroup;
use App\Models\Trip;

use Auth;
use Illuminate\Http\Request;
use Session;

class AdminController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {

		$admins = Merchant::with(['type', 'governorate'])->where('market_id', Session::get('market_id'))->latest()->paginate(10);
		return view('merchants.admins.index', compact('admins'));

	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create() {
		$groups = PermissionGroup::with(['permissions'])->where('slug', 'branches')->orWhere('slug', 'admins')->orWhere('slug', 'trips')->orWhere('slug', 'customers')->get();
		$types  = AdminType::where('active', 1)->whereIn('id', [2, 3, 4])->latest()->get();
		return view('merchants.admins.create', compact('groups', 'types'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function store(StoreAdminRequest $request) {

		// dd($request->all());
		$admin = new Merchant;
		if (!$admin->add($request->all())) {
			return back()->with('error_msg', trans('admins.adding_error'));
		}

		if ($request->hasFile('profile_picture')) {
			$path = $request->file('profile_picture')->store('merchants', 's3');
			$admin->setImage(basename($path));
		}

		$current_logged_in_admin_id = Auth::guard('merchant')->id();
		$permissions                = [];
		foreach ($request->permissions as $permission) {
			$permissions[] = new MerchantPermission([
					'permission_id' => $permission,
					'added_by'      => $current_logged_in_admin_id,
					'merchant_id'   => $admin->id,
				]);
		}

		$admin->permissions()->saveMany($permissions);

		return redirect(route('merchants.admins.index'))->with('success_msg', trans('admins.adding_success'));
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function show(Merchant $admin) {
		$admin->load(['type', 'permissions']);
		return view('merchants.admins.admin', compact('admin'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function edit(Merchant $admin) {
		$groups            = PermissionGroup::with(['permissions'])->where('slug', 'branches')->orWhere('slug', 'admins')->orWhere('slug', 'trips')->orWhere('slug', 'customers')->get();
		$types             = AdminType::where('active', 1)->whereIn('id', [2, 3, 4])->latest()->get();
		$admin_permissions = MerchantPermission::where('merchant_id', $admin->id)->pluck('permission_id')->toArray();
		return view('merchants.admins.edit', compact('groups', 'types', 'admin', 'admin_permissions'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function update(Request $request, Merchant $admin) {

		if (!$admin->edit($request->all())) {
			return back()->with('error_msg', trans('admins.updating_error'));
		}

		if ($request->hasFile('profile_picture')) {
			$path = $request->file('profile_picture')->store('merchants', 's3');
			$admin->setImage(basename($path));
		}

		$current_logged_in_admin_id = Auth::guard('merchant')->id();
		$permissions                = [];
		foreach ($request->permissions as $permission) {
			$permissions[] = new MerchantPermission([
					'permission_id' => $permission,
					'added_by'      => $current_logged_in_admin_id,
					'merchant_id'   => $admin->id,
				]);
		}

		$admin->permissions()->saveMany($permissions);

		return redirect(route('merchants.admins.index'))->with('success_msg', trans('admins.editing_success'));
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function destroy(Merchant $admin) {
		$admin->delete();
		return redirect(route('merchants.admins.index'))->with('success_msg', trans('admins.deleted_success'));
	}

	public function change_status(Request $request) {
		// dd($request->all());
		$admin = Merchant::find($request->admin_id);

		if ($admin) {
			$admin->active == 1?0:1;
			$admin->save();

		}
	}

	public function admin_trips(Merchant $admin) {

		$trips = Trip::where('admin_id', $admin->id)->latest()->get();

		return view('merchants.admins.admin_trips', compact('trips'));
	}
}

app/Http/Controllers/Merchant/MerchantController.php
<?php

namespace App\Http\Controllers\Merchant;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class MerchantController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/livewire/merchants/trips/show-trips-list.blade.php
@php
$lang = session()->get('locale');
@endphp
<div class="row">

	<div class="col-md-12">

		<div class="card-body bg-transparent">
			<ul class="list-inline mb-0 float-right">

				<li class="list-inline-item">
					<a  data-toggle="collapse" href="#search_by_trip_code_div" class="btn btn-success float-right" >
						<i class="icon-search4  "></i> @lang('trips.search_with_trip_code')
					</a>
				</li>
				<li class="list-inline-item">
					<a data-toggle="collapse" href="#advanced_search_div" class="btn btn-success float-right" >
						<i class="icon-filter3 "></i> @lang('trips.advanced_search')
					</a>
				</li>
				<li class="list-inline-item">
					<a  href="{{ route('merchants.trips.create') }}" class="btn btn-primary float-right" >
						<i class="icon-plus3 "></i> @lang('trips.add_new_trip')
					</a>
				</li>
			</ul>
		</div>

	</div>
	<div class="col-md-12">

		<div class="card collapse" id="search_by_trip_code_div" wire:ignore>
			<div class="card-body">
				<div class="form-group">
					<div class="row">
						<div class="col-md-12">
							<input type="text" id="search" wire:model="search" placeholder="@lang('trips.search_trips') ....." class="form-control" >
						</div>
					</div>
				</div>
			</div>
		</div>


		<div class="card collapse" id="advanced_search_div" wire:ignore>
			<div class="card-header bg-dark">
				@lang('trips.advanced_search')
			</div>
			<div class="card-body">
				<div class="form-group">
					<div class="row">
						<div class="col-md-2">
							<label> @lang('trips.branch') </label>
							<select wire:model="branch" class="form-control " >
								<option value="all"> @lang('trips.all_branches') </option>
								@foreach ($branches as $branch)
								<option value="{{ $branch->id }}"> {{ $branch->name }} </option>
								@endforeach
							</select>
						</div>
						<div class="col-md-2">
							<label> @lang('trips.payment_method') </label>
							<select wire:model="payment_method" class="form-control " >
								<option value="all"> @lang('trips.all_payment_methods') </option>
								@foreach ($payment_methods as $payment_method)
								<option value="{{ $payment_method->id }}"> {{ $payment_method['name_'.$lang] }} </option>
								@endforeach
							</select>
						</div>
						<div class="col-md-2">
							<label> @lang('trips.status') </label>
							<select wire:model="status" class="form-control " >
								<option value="all"> @lang('trips.all_status') </option>
								<option value="0"> @lang('trips.trip_ongoing') </option>
								<option value="1"> @lang('trips.trip_proccessing') </option>
								<option value="2"> @lang('trips.trip_cancelld') </option>
								<option value="3"> @lang('trips.trip_deliverd') </option>
							</select>
						</div>
						<div class="col-md-3">
							<label> @lang('trips.from_delivery_date') </label>
							<input type="date"  wire:model="from_delivery_date" class="form-control  ">
						</div>
						<div class="col-md-3">
							<label> @lang('trips.to_delivery_date') </label>
							<input type="date"  wire:model="to_delivery_date"  class="form-control  ">
						</div>

					</div>
				</div>
			</div>
			<div class="card-footer">

				<a wire:click="generatePDF" class="btn btn-primary text-white float-right ml-1" >
					<i class="icon-file-pdf"></i> @lang('trips.pdf')
				</a>
				<a  wire:click="generateExcel" class="btn btn-primary text-white float-right" >
					<i class="icon-file-excel"></i> @lang('trips.excel')
				</a>
			</div>
		</div>

		<div class="card" >
			<div class="card-header bg-transparent header-elements-inline">
				<h5 class="card-title"> <i class="icon-users4 mr-1"></i> @lang('trips.trips')</h5>
				<div class="header-elements">
					<div class="wmin-200">
						<select class="form-control form-control-select2 select" wire:model="paginate" >
							<option value="10">10 </option>
							<option value="15">15 </option>
							<option value="30">30</option>
							<option value="50">50</option>
							<option value="70">70</option>
							<option value="100">100</option>
							<option value="150">150</option>
						</select>
					</div>
				</div>
			</div>

			<table class="table datatable-responsive  table-bordered text-center table-hover ">
				<thead class=" bg-dark">
					<tr>
						<th>#</th>
						<th> @lang('trips.sender') </th>
						<th> @lang('trips.receiver') </th>
						<th> @lang('trips.receipt_date_from_market') </th>
						<th> @lang('trips.delivery_date_to_customer') </th>
						<th> @lang('trips.status') </th>
						<th> @lang('trips.payment_method') </th>
						<th> @lang('trips.payment_status') </th>
						<th> @lang('trips.order_price') </th>
						<th> @lang('trips.delivery_price') </th>
					</tr>
				</thead>
				<tbody>
					@php
					$i =1 ;
					@endphp
					@foreach ($trips as $trip)
					<tr>
						<td>
							<a href="#collapse-icon{{ $trip->id }}" class="text-default" data-toggle="collapse">
								<i class="icon-circle-down2"></i>
							</a>
						</td>

						<td> {{ optional($trip->branch)->name }} </td>
						<td> {{ optional($trip->address)->name }} <img src="{{ Storage::disk('s3')->url('customers/'.optional($trip->address)->image) }}" class="rounded-circle" alt="" width="40" height="40"> </td>
						<td> {{ $trip->receipt_date_from_market->toDayDateTimeString() }} </td>
						<td> {{ $trip->delivery_date_to_customer->toDayDateTimeString() }} </td>
						<td>
							@switch($trip->status)
							@case('1')
							<span class="badge badge-primary"> @lang('trips.proccessing') </span>
							@break
							@case('0')
							<span class="badge badge-secondary"> @lang('trips.inactive') </span>
							@break
							@endswitch
						</td>
						<td> {{ optional($trip->payment_method)['name_'.$lang] }} </td>
						<td>  لم يتم الدفع </td>
						<td> {{ $trip->order_price }} </td>
						<td> {{ $trip->delivery_price }} </td>
					</tr>
					<tr class="collapse " id="collapse-icon{{ $trip->id }}" >
						<td colspan="100%" >

							<div class="float-left">
								<a target="_blank"  data-popup="tooltip" title="@lang('trips.trip_details')" href="{{ route('merchants.trips.show',['trip' => $trip->id ] ) }}" class="btn btn-outline bg-primary border-primary text-primary-800 btn-icon">
									<i class="icon-eye2 text-primary-800"></i>
								</a>

								<a target="_blank"  data-popup="tooltip" title="@lang('trips.edit')" href="{{ route('merchants.trips.edit' , ['trip' => $trip->id ] ) }}" class="btn alpha-warning border-warning text-warning-800 btn-icon ml-2">
									<i class="icon-pencil7 text-warning-800"></i>
								</a>
								<a href="" data-id="{{ $trip->id }}" data-popup="tooltip" title="@lang('trips.delete_trip')" class=" delete_item btn btn-outline bg-danger border-danger text-danger-800 btn-icon border-2 ml-2"><i class="icon-trash"></i>
								</a>
							</div>
						</td>
					</tr>
					@endforeach
				</tbody>
			</table>
			<div class="card-footer bg-light ">
				<div class="float-right" >
					{{ $trips->links() }}
				</div>
			</div>
		</div>
	</div>

</div>



<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
<script>
	$(document).ready(function() {
		const Toast = Swal.mixin({
			toast: true,
			position: 'top-end',
			showConfirmButton: false,
			timer: 3000,
			timerProgressBar: true,
			didOpen: (toast) => {
				toast.addEventListener('mouseenter', Swal.stopTimer)
				toast.addEventListener('mouseleave', Swal.resumeTimer)
			}
		})

		Livewire.on('itemDeleted', itemId => {
			Toast.fire({
				icon: 'success',
				title: "@lang('trips.delete_success')",
			});
		})

		$(document).on('click', 'a.delete_item' ,  function(event) {
			event.preventDefault();
			item_id = $(this).data('id');
			confirm_deletion(item_id);
		});

		function confirm_deletion(item_id) {
			Swal.fire({
				title: 'تاكيد الحذف ',
				text: "هل انت متاكد من حذف هذه الرحله ؟",
				showCancelButton: true,
				confirmButtonColor: '#3085d6',
				cancelButtonColor: '#d33',
				confirmButtonText: 'نعم',
				cancelButtonText: 'لا',
			}).then((result) => {
				if (result.isConfirmed) {
					Livewire.emit('deleteItemConfirmed'  , item_id );
				}
			})
		}

	});



</script>